---
jenkins_repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo                 # TODO Ubuntu
jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key       # TODO Ubuntu
jenkins_init_file: /etc/sysconfig/jenkins               # TODO Ubuntu path
jenkins_http_port_param: JENKINS_PORT
